 

DROP TABLE IF EXISTS [dbo].[TicketsViaSSIS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TicketsViaSSIS](
	[TicketCode] [nvarchar](20) NOT NULL,
	[LastEditDateTime] [datetime2](7) NOT NULL,
	[AboutEE] [nvarchar](255) NULL,
	[Archived] [bit] NULL,
	[CaseType] [nvarchar](255) NULL,
	[Category] [nvarchar](255) NULL,
	[ChatAgentUserID] [nvarchar](255) NULL,
	[ClosedDateTime] [datetime2](7) NULL,
	[CloseUserID] [nvarchar](255) NULL,
	[ContactMethod] [nvarchar](255) NULL,
	[ContactName] [nvarchar](255) NULL,
	[ContactRelationshipName] [nvarchar](255) NULL,
	[CreatedDateTime] [datetime2](7) NULL,
	[CreatorFirstName] [nvarchar](255) NULL,
	[CreatorLastName] [nvarchar](255) NULL,
	[CreatorName] [nvarchar](255) NULL,
	[CreatorUserID] [nvarchar](255) NULL,
	[CustomCheckBox1] [bit] NULL,
	[CustomCheckBox2] [bit] NULL,
	[CustomCheckBox3] [bit] NULL,
	[CustomCheckBox4] [bit] NULL,
	[CustomCheckBox5] [bit] NULL,
	[CustomCheckBox6] [bit] NULL,
	[CustomDate1] [datetime2](7) NULL,
	[CustomDate2] [datetime2](7) NULL,
	[CustomDate3] [datetime2](7) NULL,
	[CustomDate4] [datetime2](7) NULL,
	[CustomDate5] [datetime2](7) NULL,
	[CustomDate6] [datetime2](7) NULL,
	[CustomSelect1] [nvarchar](255) NULL,
	[CustomSelect2] [nvarchar](255) NULL,
	[CustomSelect3] [nvarchar](255) NULL,
	[CustomSelect4] [nvarchar](255) NULL,
	[CustomSelect5] [nvarchar](255) NULL,
	[CustomSelect6] [nvarchar](255) NULL,
	[CustomString1] [nvarchar](255) NULL,
	[CustomString2] [nvarchar](255) NULL,
	[CustomString3] [nvarchar](255) NULL,
	[CustomString4] [nvarchar](255) NULL,
	[CustomString5] [nvarchar](255) NULL,
	[CustomString6] [nvarchar](255) NULL,
	[Email] [nvarchar](255) NULL,
	[FirstName] [nvarchar](255) NULL,
	[IsFirstCallResolution] [nvarchar](255) NULL,
	[Issue] [nvarchar](3000) NULL,
	[KnowledgeDomain] [nvarchar](255) NULL,
	[LastEditUserID] [nvarchar](255) NULL,
	[LastName] [nvarchar](255) NULL,
	[OwnerUserID] [nvarchar](255) NULL,
	[Population] [nvarchar](255) NULL,
	[Priority] [nvarchar](255) NULL,
	[ProcessTime] [smallint] NULL,
	[RegardingUserID] [nvarchar](255) NULL,
	[ReminderDateTime] [datetime2](7) NULL,
	[ReminderEmail] [nvarchar](255) NULL,
	[ReminderNote] [nvarchar](1000) NULL,
	[ReminderPhone] [nvarchar](255) NULL,
	[Resolution] [nvarchar](3000) NULL,
	[ResolvedDateTime] [datetime2](7) NULL,
	[Secure] [nvarchar](255) NULL,
	[ServiceGroup] [nvarchar](255) NULL,
	[ShowToEE] [nvarchar](255) NULL,
	[SLA] [datetime2](7) NULL,
	[Source] [nvarchar](255) NULL,
	[SubCategory] [nvarchar](255) NULL,
	[Subject] [nvarchar](1000) NULL,
	[SubStatus] [nvarchar](255) NULL,
	[SurveyAgreementResponse] [nvarchar](255) NULL,
	[SurveyAnswer1] [nvarchar](255) NULL,
	[SurveyAnswer2] [nvarchar](255) NULL,
	[SurveyAnswer3] [nvarchar](255) NULL,
	[SurveyAnswer4] [nvarchar](255) NULL,
	[SurveyAnswer5] [nvarchar](255) NULL,
	[SurveyCommentResponse] [nvarchar](1000) NULL,
	[SurveyDateTime] [datetime2](7) NULL,
	[SurveyFollowup] [nvarchar](255) NULL,
	[SurveyID] [nvarchar](255) NULL,
	[SurveyScore] [nvarchar](255) NULL,
	[TicketStatus] [nvarchar](255) NULL,
	[Topic] [ntext] NULL,
	[UserID] [nvarchar](255) NULL,
	[CreateDate] [datetime2](7) NULL,
	[SLADate] [datetime2](7) NULL,
	[ClosedDate] [datetime2](7) NULL,
	[LoadStamp] [datetime2](7) NULL,
	[SourceFileStamp] [nvarchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


